### ISSUE TITLE
Error con algunos dominios

### ISSUE THREAD

**Issue by Gaiztoa** [UnaPibaGeek/ctfr#10]
Ejemplo:
python ctfr.py -d madrid.es

File "ctfr.py", line 80, in <module>
    main()
  File "ctfr.py", line 62, in main
    json_data = json.loads('[{}]'.format(req.text.replace('}{', '},{')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 480: ordinal not in range(128)

Gracias por el programa.

**Comment by David256** [comment]
@Gaiztoa El `README.md` dice que se requiere `python 3.0 en adelante`.
Al usar `python ctfr.py`, se está usando la versión 2.x de python, al menos que no.

**Comment by Gaiztoa** [comment]
Efectivamente, era eso y estaba delante de mis narices...

Gracias.
