### ISSUE TITLE
Missleading description

### ISSUE THREAD

**Issue by kinduff** [UnaPibaGeek/ctfr#13]
Since the tool is making an HTTP request to [CRT.sh](https://crt.sh) and parsing the JSON, the description should state this instead of mentioning that the tool itself is abusing certificate transparency logs.

**Comment by UnaPibaGeek** [comment]
crt.sh is already mentioned in the README.
CT logs abuse _is a concept_, and that concept is the one behind this tool, regardless the API used to do that.

**Comment by kinduff** [comment]
Thanks for adding CRT.sh to the README 50f1b07
