### ISSUE TITLE
unicode error

### ISSUE THREAD

**Issue by ghost** [UnaPibaGeek/ctfr#14]
Traceback (most recent call last):
  File "ctfr.py", line 71, in <module>
    main()
  File "ctfr.py", line 53, in main
    json_data = json.loads('[{}]'.format(req.text.replace('}{', '},{')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 51138: ordinal not in range(128)

**Comment by UnaPibaGeek** [comment]
You are using python 2.x, check the readme, python 3.x is required.
